# Generated by Django 4.2.dev20220718043020 on 2022-07-21 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=10, verbose_name='Uzvārds')),
                ('forename', models.CharField(max_length=10, verbose_name='Vārds')),
                ('student_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{8}$')], verbose_name='Studenta kods')),
                ('aktivs', models.BooleanField(choices=[(1, 'Aktīvs'), (0, 'Nav aktīvs')], default=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
