# Generated by Django 4.2.dev20220718043020 on 2022-07-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6}$')], verbose_name='Kursa kods')),
                ('module_name', models.CharField(max_length=50, verbose_name='Kursa nosaukums')),
                ('var_atzimes', models.BooleanField(choices=[(True, 'Drīkst ievadīt atzīmes'), (False, 'Nedrīkst ievadīt atzīmes')], verbose_name='Atzīmju ievadīšana')),
                ('aktivs', models.BooleanField(choices=[(True, 'Kurss ir redzams'), (False, 'Kurss nav redzams')], verbose_name='Kurss ir aktīvs')),
            ],
            options={
                'db_table': 'modules',
                'unique_together': {('id', 'module_code')},
            },
        ),
    ]
