# Generated by Django 4.2.dev20220718043020 on 2022-07-21 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6}$')], verbose_name='Kursa kods')),
                ('module_name', models.CharField(max_length=50, verbose_name='Kursa nosaukums')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
